import {initializeApp} from "https://www.gstatic.com/firebasejs/12.4.0/firebase-app.js";
import {getAuth,onAuthStateChanged,GoogleAuthProvider,signInWithPopup,signOut} from "https://www.gstatic.com/firebasejs/12.4.0/firebase-auth.js";
import {getFirestore,collection,getDocs,getDoc,doc,query,orderBy,limit,setDoc,deleteDoc,serverTimestamp,where,addDoc} from "https://www.gstatic.com/firebasejs/12.4.0/firebase-firestore.js";
import {firebaseConfig} from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let user=null,admin=false,animeCache=[];

onAuthStateChanged(auth,async u=>{user=u; if(u){const a=await getDoc(doc(db,"admins",u.uid));admin=a.exists()}else admin=false; renderAuth();$("#adminLink").hidden=!admin; route();});
function renderAuth(){$("#auth").innerHTML=user?`<button class="btn ghost" id="logout">Sign out</button>`:`<button class="btn" id="login">Sign in</button>`;if($("#logout"))$("#logout").onclick=()=>signOut(auth);if($("#login"))$("#login").onclick=()=>signInWithPopup(auth,new GoogleAuthProvider())}
async function getAnime(){const s=await getDocs(query(collection(db,"anime"),orderBy("title")));return s.docs.map(d=>({id:d.id,...d.data()}))}
function card(a){return `<article class="card"><a href="#/anime/${a.id}"><div class="poster" style="background-image:url('${esc(a.poster)}')"></div></a><div class="body"><button class="heart" onclick="fav(event,'${a.id}')">♥</button><b>${esc(a.title)}</b><div class="muted">${esc(a.year||"")} • ${esc(a.genre||"")}</div></div></article>`}
async function home(){animeCache=await getAnime();$("#app").innerHTML=`<section class="hero"><small>YOUR ANIME HUB</small><h1>Watch. Discover.<br>Enjoy.</h1><p>Anime catalog, episode pages, favorites and watch history, backed by Firebase.</p></section><div class="row"><h2>Anime Catalog</h2><input id="search" class="search" placeholder="Search anime…"></div><div id="grid" class="grid">${animeCache.map(card).join("")}</div>`;$("#search").oninput=e=>$("#grid").innerHTML=animeCache.filter(a=>a.title.toLowerCase().includes(e.target.value.toLowerCase())).map(card).join("")}
async function animePage(id){const a=(await getDoc(doc(db,"anime",id)));if(!a.exists())return msg("Anime not found.");const x={id:a.id,...a.data()};const eps=await getDocs(query(collection(db,"anime",id,"episodes"),orderBy("number")));$("#app").innerHTML=`<section class="detail"><img src="${esc(x.poster)}"><div><h1>${esc(x.title)}</h1><p class="muted">${esc(x.year||"")} • ${esc(x.genre||"")} • ★ ${esc(x.rating||"")}</p><p>${esc(x.description||"")}</p><button class="btn" onclick="fav(event,'${id}')">♥ Favorite</button><h2>Episodes</h2><div class="episodes">${eps.docs.map(e=>`<a class="ep" href="#/watch/${id}/${e.id}">Episode ${esc(e.data().number)}</a>`).join("")||"<p class='muted'>No episodes yet.</p>"}</div></div></section>`}
async function watch(aid,eid){const [a,e]=await Promise.all([getDoc(doc(db,"anime",aid)),getDoc(doc(db,"anime",aid,"episodes",eid))]);if(!a.exists()||!e.exists())return msg("Episode not found.");const x=a.data(),ep=e.data();$("#app").innerHTML=`<h1>${esc(x.title)} — Episode ${esc(ep.number)}</h1><video class="video" controls autoplay src="${esc(ep.videoUrl)}"></video><p>${esc(ep.title||"")}</p><a class="btn" href="#/anime/${aid}">Back to episodes</a>`;if(user)await setDoc(doc(db,"users",user.uid,"history",aid+"_"+eid),{animeId:aid,episodeId:eid,title:x.title,episodeNumber:ep.number,updatedAt:serverTimestamp()})}
async function fav(ev,id){ev?.preventDefault();if(!user)return alert("Sign in first.");const r=doc(db,"users",user.uid,"favorites",id);const old=await getDoc(r);old.exists()?await deleteDoc(r):await setDoc(r,{animeId:id,createdAt:serverTimestamp()});alert(old.exists()?"Removed from favorites":"Added to favorites")}
async function listUser(kind){if(!user)return msg("Sign in to see this page.");const s=await getDocs(collection(db,"users",user.uid,kind));const ids=s.docs.map(d=>kind==="favorites"?d.id:d.data().animeId);const all=await getAnime();const selected=all.filter(a=>ids.includes(a.id));$("#app").innerHTML=`<h1>${kind==="favorites"?"Favorites":"Watch History"}</h1><div class="grid">${selected.map(card).join("")||"<p class='muted'>Nothing here yet.</p>"}</div>`}
async function adminPage(){if(!admin)return msg("Admin access required.");const all=await getAnime();$("#app").innerHTML=`<section class="admin"><h1>Admin Panel</h1><p class="muted">Create anime and episodes. Firestore rules enforce admin access.</p><h2>Add Anime</h2><form id="af"><input name="title" placeholder="Title" required><input name="poster" placeholder="Poster image URL" required><input name="year" type="number" placeholder="Year"><input name="genre" placeholder="Genre"><input name="rating" placeholder="Rating"><textarea name="description" placeholder="Description"></textarea><button class="btn">Create Anime</button></form><h2>Anime</h2><table><tbody>${all.map(a=>`<tr><td>${esc(a.title)}</td><td><button class="btn" onclick="addEpisode('${a.id}')">Add episode</button></td></tr>`).join("")}</tbody></table></section>`;$("#af").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await addDoc(collection(db,"anime"),{title:f.get("title"),poster:f.get("poster"),year:Number(f.get("year")||0),genre:f.get("genre"),rating:f.get("rating"),description:f.get("description"),createdAt:serverTimestamp()});adminPage()}}
async function addEpisode(id){if(!admin)return;const n=prompt("Episode number?");const url=prompt("Licensed video URL?");if(!n||!url)return;await addDoc(collection(db,"anime",id,"episodes"),{number:Number(n),title:"Episode "+n,videoUrl:url,createdAt:serverTimestamp()});alert("Episode added.")}
function msg(t){$("#app").innerHTML=`<div class="notice">${esc(t)}</div>`}
async function route(){const p=location.hash.slice(2).split("/");try{if(!p[0])return home();if(p[0]==="anime")return animePage(p[1]);if(p[0]==="watch")return watch(p[1],p[2]);if(p[0]==="favorites")return listUser("favorites");if(p[0]==="history")return listUser("history");if(p[0]==="admin")return adminPage();home()}catch(e){console.error(e);msg(e.message||"Something went wrong.")}}
window.addEventListener("hashchange",route);window.fav=fav;window.addEpisode=addEpisode;